In [49]:
import pandas as pd
import numpy as np

**Question 1 - Pandas Version**

In [3]:
pd.__version__

'2.2.2'

**Question 2 - Records Count**

In [4]:
df = pd.read_csv("C:\\Users\\hp\\Documents\\ML ZoomCamp Files\\laptops.csv")

In [6]:
df.shape

(2160, 12)

**Question 3 - Laptop Brands**

In [7]:
brands_count = df['Brand'].nunique()

In [8]:
print(brands_count)

27


**Question 4 - Columns with Missing values**

In [9]:
columns_with_missing_values = df.isna().sum() > 0 

In [10]:
num_columns_with_missing = columns_with_missing_values.sum()

In [11]:
print(num_columns_with_missing)

3


**Question 5 - Max Value Final Price**

In [12]:
max_value = df['Final Price'].max()

In [13]:
print(max_value)

7150.47


*Max final price of Dell Notebooks*

In [14]:
Dell_only = df[df['Brand'] == 'Dell']

*Maximum value for the Price of Dell Laptop Brand*

In [15]:
max_dell_price = Dell_only['Final Price'].max()

In [16]:
print(max_dell_price)

3936.0


**Question 6 - Median Value  of Screen**

In [17]:
median_screen_value = df['Screen'].median()

In [18]:
print(median_screen_value)

15.6


*Mode for Screen Column*

In [19]:
mode_screen_value = df['Screen'].mode()

*Fill mising Screen Values with Mode*

In [20]:
df["Screen"] = df["Screen"].fillna(mode_screen_value)

In [21]:
mode_screen_value = df['Screen'].mode()

In [24]:
print(mode_screen_value)

0    15.6
Name: Screen, dtype: float64


**Question 7 - Sum of Weights**

*Injoo Laptops with RAM, Storage, and Screen*

In [26]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

*Select Innjoo Brand*

In [39]:
innjoo_laptops = df[df['Brand'] == 'Innjoo']

In [40]:
innjoo_laptops.head()

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02

*Select only the columns 'RAM', 'Storage', and 'Screen'*

In [41]:
innjoo_laptops_new = innjoo_laptops[['RAM', 'Storage', 'Screen']]

In [44]:
display(innjoo_laptops_new)

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

*Convert dataset to array*

In [45]:
injoo_array = innjoo_laptops_new.to_numpy()

In [46]:
X = injoo_array

In [47]:
print(X)

[[  8.  256.   15.6]
 [  8.  512.   15.6]
 [  4.   64.   14.1]
 [  6.   64.   14.1]
 [  6.  128.   14.1]
 [  6.  128.   14.1]]


*Compute the transpose of X*

In [48]:
X_transpose = X.T

*Matrix Multiplication: X^T x X*

In [53]:
XTX = np.dot(X_transpose, X)

*Inverse of XTX*

In [54]:
XTX_inverse = np.linalg.inv(XTX)

*Create y array values*

In [55]:
y = [1100, 1300, 800, 900, 1000, 1100]

*Multiply inverse of XTX with transpose of X, and multiply the result by y. Call the result w*

In [57]:
w_int = np.dot(XTX_inverse, X_transpose)

In [58]:
w = np.dot(w_int, y)

In [59]:
w_sum = w.sum()

In [60]:
print(w_sum)

91.29988062995815
